### ISSUE TITLE
Incompatible with latest IDE

### ISSUE THREAD

**Issue by adamwoolhether** [milankinen/intellij-iceberg-theme#5]
Love the theme, it's my favorite! The latest JetBrains release breaks it, however.

<img width="405" alt="Screen Shot 2021-12-09 at 08 10 49" src="https://user-images.githubusercontent.com/29599403/145311142-161ed6ac-1296-4f34-bfea-f9853c3a9897.png">

**Comment by milankinen** [comment]
Thanks! This issue is hopefully solved in [`0.7.0`](https://github.com/milankinen/intellij-iceberg-theme/releases/tag/v0.7.0) which should become available after JetBrains has reviewed it (usually takes 1-2 business days). Meanwhile you can also install the plugin manually from the release artifact zip.

**Comment by milankinen** [comment]
The new version should be available at JetBrains marketplace now. @adamwoolhether could you confirm whether the issue is fixed or not?

**Comment by adamwoolhether** [comment]
> The new version should be available at JetBrains marketplace now. @adamwoolhether could you confirm whether the issue is fixed or not?

It works wonderfully, thanks!
